[package]
name = "kick-bot"
version = "0.1.0"
edition = "2021"

[dependencies]
console = "0.16.1"
crossterm = "0.29.0"
rand = "0.9.2"
serde = { version = "1.0.228", features = ["derive"] }
toml = "0.9.8"
